auth:
  providers:
    saml:
      name: MyUB
      enabled: true
      entryPoint: https://samltest.id/idp/profile/SAML2/Redirect/SSO
      attributeMap:
        urn:oid:0.9.2342.19200300.100.1.3: email
        urn:oid:0.9.2342.19200300.100.1.1: externalId
        urn:oasis:names:tc:SAML:attribute:subject-id: identifier
        urn:oid:2.5.4.4: sn
        urn:oid:2.16.840.1.113730.3.1.241: displayName
        urn:oid:2.5.4.20: telephoneNumber
        urn:oid:2.5.4.42: givenName
        https://samltest.id/attributes/role: role
        urn:oid:1.3.6.1.4.1.5923.1.1.1.7: eduPersonEntitlement
      idpCerts:
        - |
          -----BEGIN CERTIFICATE-----
          MIIDETCCAfmgAwIBAgIUZRpDhkNKl5eWtJqk0Bu1BgTTargwDQYJKoZIhvcNAQEL
          BQAwFjEUMBIGA1UEAwwLc2FtbHRlc3QuaWQwHhcNMTgwODI0MjExNDEwWhcNMzgw
          ODI0MjExNDEwWjAWMRQwEgYDVQQDDAtzYW1sdGVzdC5pZDCCASIwDQYJKoZIhvcN
          AQEBBQADggEPADCCAQoCggEBAJrh9/PcDsiv3UeL8Iv9rf4WfLPxuOm9W6aCntEA
          8l6c1LQ1Zyrz+Xa/40ZgP29ENf3oKKbPCzDcc6zooHMji2fBmgXp6Li3fQUzu7yd
          +nIC2teejijVtrNLjn1WUTwmqjLtuzrKC/ePoZyIRjpoUxyEMJopAd4dJmAcCq/K
          k2eYX9GYRlqvIjLFoGNgy2R4dWwAKwljyh6pdnPUgyO/WjRDrqUBRFrLQJorR2kD
          c4seZUbmpZZfp4MjmWMDgyGM1ZnR0XvNLtYeWAyt0KkSvFoOMjZUeVK/4xR74F8e
          8ToPqLmZEg9ZUx+4z2KjVK00LpdRkH9Uxhh03RQ0FabHW6UCAwEAAaNXMFUwHQYD
          VR0OBBYEFJDbe6uSmYQScxpVJhmt7PsCG4IeMDQGA1UdEQQtMCuCC3NhbWx0ZXN0
          LmlkhhxodHRwczovL3NhbWx0ZXN0LmlkL3NhbWwvaWRwMA0GCSqGSIb3DQEBCwUA
          A4IBAQBNcF3zkw/g51q26uxgyuy4gQwnSr01Mhvix3Dj/Gak4tc4XwvxUdLQq+jC
          cxr2Pie96klWhY/v/JiHDU2FJo9/VWxmc/YOk83whvNd7mWaNMUsX3xGv6AlZtCO
          L3JhCpHjiN+kBcMgS5jrtGgV1Lz3/1zpGxykdvS0B4sPnFOcaCwHe2B9SOCWbDAN
          JXpTjz1DmJO4ImyWPJpN1xsYKtm67Pefxmn0ax0uE2uuzq25h0xbTkqIQgJzyoE/
          DPkBFK1vDkMfAW11dQ0BXatEnW7Gtkc0lh2/PIbHWj4AzxYMyBf5Gy6HSVOftwjC
          voQR2qr2xJBixsg+MIORKtmKHLfU
          -----END CERTIFICATE-----
        - |
          -----BEGIN CERTIFICATE-----
          MIIDEjCCAfqgAwIBAgIVAMECQ1tjghafm5OxWDh9hwZfxthWMA0GCSqGSIb3DQEB
          CwUAMBYxFDASBgNVBAMMC3NhbWx0ZXN0LmlkMB4XDTE4MDgyNDIxMTQwOVoXDTM4
          MDgyNDIxMTQwOVowFjEUMBIGA1UEAwwLc2FtbHRlc3QuaWQwggEiMA0GCSqGSIb3
          DQEBAQUAA4IBDwAwggEKAoIBAQC0Z4QX1NFKs71ufbQwoQoW7qkNAJRIANGA4iM0
          ThYghul3pC+FwrGv37aTxWXfA1UG9njKbbDreiDAZKngCgyjxj0uJ4lArgkr4AOE
          jj5zXA81uGHARfUBctvQcsZpBIxDOvUUImAl+3NqLgMGF2fktxMG7kX3GEVNc1kl
          bN3dfYsaw5dUrw25DheL9np7G/+28GwHPvLb4aptOiONbCaVvh9UMHEA9F7c0zfF
          /cL5fOpdVa54wTI0u12CsFKt78h6lEGG5jUs/qX9clZncJM7EFkN3imPPy+0HC8n
          spXiH/MZW8o2cqWRkrw3MzBZW3Ojk5nQj40V6NUbjb7kfejzAgMBAAGjVzBVMB0G
          A1UdDgQWBBQT6Y9J3Tw/hOGc8PNV7JEE4k2ZNTA0BgNVHREELTArggtzYW1sdGVz
          dC5pZIYcaHR0cHM6Ly9zYW1sdGVzdC5pZC9zYW1sL2lkcDANBgkqhkiG9w0BAQsF
          AAOCAQEASk3guKfTkVhEaIVvxEPNR2w3vWt3fwmwJCccW98XXLWgNbu3YaMb2RSn
          7Th4p3h+mfyk2don6au7Uyzc1Jd39RNv80TG5iQoxfCgphy1FYmmdaSfO8wvDtHT
          TNiLArAxOYtzfYbzb5QrNNH/gQEN8RJaEf/g/1GTw9x/103dSMK0RXtl+fRs2nbl
          D1JJKSQ3AdhxK/weP3aUPtLxVVJ9wMOQOfcy02l+hHMb6uAjsPOpOVKqi3M8XmcU
          ZOpx4swtgGdeoSpeRyrtMvRwdcciNBp9UZome44qZAYH1iqrpmmjsfI9pJItsgWu
          3kXPjhSfj1AJGR1l9JGvJrHki1iHTA==
          -----END CERTIFICATE-----
      encryption:
        privateKey: |
          -----BEGIN PRIVATE KEY-----
          MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDvoSlEze+FiQb2
          tk5/mygImICe6bzHdNNubs3ASoLZwHmYJaFvwmAT1hNMfxm8Ewnkc39y88MAD9BN
          4g8QhOm9ZHRxIkPalXKe8i2kzSaFuUu+aeya9ljy6uwnvvfGAvm3dLO9Xxcku6Bb
          5XkCg0nuhDK78FvsvFAS2tdkmrwI9dMhzwtGK50yAg9KFpA8CqH4/XcUTqSkFXgC
          MtLh3qWV1INBDLp80bhe6UZTqj5wVFdEC9x4slX+DaqcLsSYYv+xtqn+cchpQSOe
          ONH8k9Eh+OHP/qCCNI0wodCYuEybfZIyuu8RfcJWBUnv/GXZXLdbzwVxw9bLR/7m
          ZDkhIl4iOatfewuuEQt3jPeifaKa0nyOirHBK1A6hHJ2NObH0ZC2/DU6gM3P+myi
          6K/P9mm8+uefQFza0L+syOBFos+gfWQWirRshW/l8DI+CTS0ZQri3yKXvHHB1MWI
          HId7eKlthRiFt99e6Qmr20+xh7CL697vubSvRRiFGwHbxkx1KtWnY8Gajq96pjKm
          DMQAI8PIAfLsFeB+KZC24maAFGy1QIie/HietkAVEs6GbZcvhdQLHNOkfCj5yhAO
          tDOHOM+DR7d9gB61wv1bbLq74ptlJ/3RCSK+XzrO4OgP8HogHRLVucYTnGFhcoBL
          8L3pJaUjGNGrcrW+8e6MqLpH8TPZ+QIDAQABAoICAQCxJxHdXemPbQgK6CgMSmZE
          RIoB8YawZfvRDnVpjSxDUvoRsvAwMSDaSU8nJGegFOshSwmTsAYfS5GRomfErJ4o
          d9VlthE3zXhZbWy1Az1RavVGJgTXYvvLSkWf9Jw0dQqrx8kBXQU9EMCyb2kQpILJ
          pE3lhwJOd8Eyzzqhk4sjjKizu97311J1H/SxrxCecrXf33JjPuiUrZJ0/aHNfc4o
          gF0wf/p2QIzvDcICJD/Yx2FkWuh5Ck5sbSoOIL0Sc03Y0dPG2dNxjMiKNjN3aMgZ
          N2epXvLGj5c5tscBwG5SHXkxq+UFp1U+RtasZondMaAUbW329vMagXU+WiWqC0BO
          2spAYqZpMjevusDQggHaQEo/mon1ikGO2YkdtVd5VE4yrXx8Rk2FKJ9b0OOLf2kF
          dHF0sAJ53Lto3ghkwUa+s0TUsGjtkCWeWdcE7rX1mX1kZPuvpgKzK6B7WKjTA4UV
          Opdm+irc0gPj7AquE/po4Urnqd2LhunGyaaaQUGqoiDrDH5vaFrY/hZcag8B7q68
          Wl7ORXROSwb4QELZYzixi798Wtbm9wZlWXl+dObbOEjJQkBUvzpgOjEb/f6yOG+0
          mnK2/d8K54nYHt0j9yxodh/Ew6cgU1jEbZn6mItbhbT1C+bGAvGh/fsOf7Kti5vu
          4EOl0HXLtVB1RY/DJnJDAQKCAQEA/TDIk6t6sCwPJ63Dgii0XGZbsXtyvUw0WHHO
          d9eULbzRwSvXJ9U4UFv6j7A/7FpcHBPaZE/JsFfLGyyxfM9a8OMWZMlSwu7a1UjW
          jGqxUvrtCyq5mWBG5rv/s8oLt5ohK2jjvEmt/vtSsWFoCHwANAWoY+G4Bpd9wlzK
          Z29SWrJur1xdCw5+d+t3vI326IEZKV5/N8znxaA4T/dLPKRCu8P03WFvjXWpp9cZ
          I9pGbkD0cfic/+d0C0tgIDauJCzT5QGTu6+++tj+4A6gvN/SiZoJUGWGR3b0F7R9
          AbNFicZxWiiy1BnT350p1cgPOUK+dM2GlDyd0Yj8jXBjP69OyQKCAQEA8knbJ7e4
          6vRtUV2i5rV9UtHsBTJf8x6Nsg19ADBmzIFAa4kpgcYM6+4e0dTgyrRgUuAwxKM+
          YZcvKb9xI8Yg/tZS1T9TEp8QM5nY6S/RjcA1DUwJCE8tmuH2btN2DPSp+GsoMYh8
          pyNmNxLfGU9XNZf8q85kq0/JCD07LT0h8pRqVUznVM1vkvAUg/7PUpyAiHCIySOZ
          RK8zeOBKx+ZD2YvtM+xYHqYxIK6zedWuKUEOAc7UNrcZsvfBEMbbY5C0QaXwGtLI
          CctnwgrkmztY8tLZ+ZUdfd+7rv3eTwFrSEwyqLOBzrz5po790qEn7o2vneJb542D
          blep1q2ogobZsQKCAQEAtV8T4AzP95GoTZFBY2ULRsGgX7SCDi6ftNfZwqmwoU8I
          pytjlko8a/xnsjTcpdBY+VgTcxZg8a0CdvX+Mt1LVRInwY0idzeplW33G2F2o23T
          DtPNXpzETZdQ5hcPa7fCmRkrQn85YFXi9+RCJQnHD30aEmroa/hrgyb7azsosIXv
          mjk9AaWhXQBVpsG/pPCN+L+TvIJRaZWLoWUSBV/Z2i3WpBufUKOAJBaHENLU7zgi
          o94ngX3o+ApH0uu4tXtTU1Jc5O9RjNqTQifYZ1SiuiWZFHmVxm3lD3Igtm4Ym0iH
          fMF40U2rJB2ukVEd7rPsQTnVdS0zFJ3f5OYkgsNvWQKCAQBgt2y9WRB+8d1lenxZ
          nh8N3XBazrYQhaTIa6v3VFrkzb+abaFdBWMJFv/EgTbOk9xTmNy+0e9H46LXBm2y
          exeWwpVEPMf7ifVcs9ArnYQIEq7axPxiDcFFr2fA67aXC1+CI7xisXoY+f+Ggoj+
          QHaulSIuru/ulqXIHTEvKNURUX9014MMjgk43Y9C9YdrEcAZNtrTd9tp2IoyeU5A
          p8Fz6PBiJrkyWuMHidVpEAw6uZZO0HJT+RlQIKg3+zl+cDgUcJn9CyEBD+o2QkTp
          VnJ2VAbhI04nfhUckIiafxWFQa2DPEzX6wW5ICFgYCZhiruMydwn/Yx2kpXgdWfr
          2sqxAoIBAQCJmxd5kNYG/QJbiTgXcoMutsrS5PcWTP/PYUVZSijLvqXoIegSfsNh
          DeirRd8l3NSYu3CyNFxKYVtC70LYZmoulwDo12CUdCq+mDhk3Xtz+QUfr9mSUqO5
          5/+dzlXTxkuoIpPqYOMLngOA23e3WOJQ9Yh+WwSZSbHZVEU/9XdYv7w480b7UGnM
          tNK1FCk75OgsX8alLzpk82sctTbq9Y6oGto6fv1yIGOAfu9c7z2RnKiWK6qjS26f
          gufaOqMD/wp1jVp4ECC+tECOgI3i33e+Lb9btkS0Gs5Dv0K27KQ1SOau2U8B9SZx
          ITrYWDQgr92ZQw8XnsvvSlrEgPcDLj7m
          -----END PRIVATE KEY-----
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIFozCCA4ugAwIBAgIUIIFZiR0wI7dsTyzRCVnIlQQkCk4wDQYJKoZIhvcNAQEL
          BQAwYTELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE5ldyBZb3JrMRAwDgYDVQQHDAdC
          dWZmYWxvMQ0wCwYDVQQKDAREZXZVMR4wHAYDVQQDDBVkZXZ1LWVuY3J5cHRpb24u
          bG9jYWwwHhcNMjEwNjA2MjAzMzE4WhcNMjMxMTIzMjAzMzE4WjBhMQswCQYDVQQG
          EwJVUzERMA8GA1UECAwITmV3IFlvcmsxEDAOBgNVBAcMB0J1ZmZhbG8xDTALBgNV
          BAoMBERldlUxHjAcBgNVBAMMFWRldnUtZW5jcnlwdGlvbi5sb2NhbDCCAiIwDQYJ
          KoZIhvcNAQEBBQADggIPADCCAgoCggIBAO+hKUTN74WJBva2Tn+bKAiYgJ7pvMd0
          025uzcBKgtnAeZgloW/CYBPWE0x/GbwTCeRzf3LzwwAP0E3iDxCE6b1kdHEiQ9qV
          cp7yLaTNJoW5S75p7Jr2WPLq7Ce+98YC+bd0s71fFyS7oFvleQKDSe6EMrvwW+y8
          UBLa12SavAj10yHPC0YrnTICD0oWkDwKofj9dxROpKQVeAIy0uHepZXUg0EMunzR
          uF7pRlOqPnBUV0QL3HiyVf4NqpwuxJhi/7G2qf5xyGlBI5440fyT0SH44c/+oII0
          jTCh0Ji4TJt9kjK67xF9wlYFSe/8Zdlct1vPBXHD1stH/uZkOSEiXiI5q197C64R
          C3eM96J9oprSfI6KscErUDqEcnY05sfRkLb8NTqAzc/6bKLor8/2abz6559AXNrQ
          v6zI4EWiz6B9ZBaKtGyFb+XwMj4JNLRlCuLfIpe8ccHUxYgch3t4qW2FGIW3317p
          CavbT7GHsIvr3u+5tK9FGIUbAdvGTHUq1adjwZqOr3qmMqYMxAAjw8gB8uwV4H4p
          kLbiZoAUbLVAiJ78eJ62QBUSzoZtly+F1Asc06R8KPnKEA60M4c4z4NHt32AHrXC
          /Vtsurvim2Un/dEJIr5fOs7g6A/weiAdEtW5xhOcYWFygEvwveklpSMY0atytb7x
          7oyoukfxM9n5AgMBAAGjUzBRMB0GA1UdDgQWBBTPCRH6MW3H4WwXHknEDMgamqf2
          IjAfBgNVHSMEGDAWgBTPCRH6MW3H4WwXHknEDMgamqf2IjAPBgNVHRMBAf8EBTAD
          AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCvJj37zfD7zZvRJOjNeQn1ZPyrnxMaXp2W
          VLEboifwD4JXYFdwFFJtpxOpEksF9wEf+rIh6wjNkEZ9P1eKGZSWAsB+30juOCZt
          n8m5w1r013DUu5o74sTg58bX2qJkrm5ZsOt0/95S9qSg0m+PMNW+6OezULMyOgfU
          tZe2HvQWvPwYpa0zmr3ker6UkdLw/a/rrhrC/PcBHafz+dpZWSm0Ln8WPV0fF/uz
          2I+vmfgVOIxx/EM/BMcZxk1TpFliWULQS3Dfl1IALlJV5uJvkMv7uBm4PvZaEX3N
          z+tGfQ0ABeMHTNhYDCGRYAU8eCOzOkYWSIHi7fpYfI9G9Hinquiq7vLJ3zM5McEz
          s1bidLFD+Y0qAPm4Az8X4+3UBUKG3WfQXMaU7htvBQMPVHkFgEfvbsmmdPVny7SZ
          dhtVV1id/BAqHpfFgzX5jb2iM7G2+q+sDV+Trwr15xoGE6JlrKCpHJD/ZqKvv4UB
          o0e9mShvgLuUJThhFZquennTYNyQ1PkhQdxnkZmzwNqkaxrw8mbOaffEZ2oHHeEZ
          UBnL+k58TodVUg6yTJz+jBMD6MA1p2sL6jvtDtA/K/MhVgJuY+y73/dlfOGnu4co
          yMccCkt5X/PGdXqZcKHnIF+v4qFNg551I2Zj2CMbXEV2lWOjcbb4vAjhlEJK1SuQ
          M/BhasEcgg==
          -----END CERTIFICATE-----
      signing:
        privateKey: |
          -----BEGIN PRIVATE KEY-----
          MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDn+WdhqDs3UGa2
          TzFgUrhr6C6JD+DXN/PO+Uxu8c6BBx0RwKezB+uQafmUYcSbN/G3DCrFsZtr2QPB
          Vm0KwMaCJpXtZM492A/tx+9iznvzcXwx+6QcgGZSZP5Qop1w+608GfCTxzy96bc5
          NGeV6ZQBFqZG1LrYjK87WEUTwYc1TPL8sw+zMJsu12n74PXACBT0/PtUC0Gx2/D3
          JaEeFS+6dJA5+sGfag4iujawzo+xlm6j+AIwWmwn1USTGRThspnfJkGrzpIowWlF
          gvkLF2HAuI33zdk/83wEKtzL+Vz5uO2A4kXp0MFy7OvyXq+oXnGxwbAqfMhX/s8o
          d5Y/JD/PsmTcnPjA/sEmZiZbKfAZYUQ5mVdpTdm4ZSThjJZ7MY/B/bgwvpoLcnLD
          jGZ/PKFV1yeKiHoit/hO5hU0dHtmaCRgLcjaUMPrdexTeKBPPrXDCOSUfvazXbgf
          RHF+yrPGrKZhLbxZf3hn8qWRDTaPSWp7pL/myBz3pzs9I0AJChwJw+3qWK4VryTv
          0Jave5OIwMSC5GxtHASZw+s2a0VmQxjdjGpPxfsPy+ChMz4oPJiPXCgUCRC1sewV
          pA5AZxfZuMwYgCqK0LTFGk24LQGTDlNAEAp/9WFdryEGIcul+ZZJ1zWH9EfwVpa+
          Sve/aXlIJeIeaJYBt9VM+p74m31L3wIDAQABAoICAQCEoOXoweTJZWC0T2btqZ3j
          pCYnGzr0EfuFlKeMrxfgUY7fPYUkKR0Xvl+B5Lwh+sRqYbx6t2cjLDqnaaCCi2Fz
          vFfwGLiKR2QkETHfDit0LqhRc4yK9yaJaVC2DaNym5KaUEJqW3lxI5UsUbf/0EJc
          tPRwfuQtN5JgncEw4G9LnCk5La+GRf4Ts/nWlvIqzvQcdh/EF4OCCzwkMhGCP57A
          PjDP1Xyqhlp6pHjscc1aPaYYfY3S04AO7jJ839Q+jnzHRvo5HqwWPS7RHWcCXmX3
          aA1TZxAVLkLzpwYCYRo1dPPlwnkyi7Zu3OKx+kz4OLdMaG8ue5WYKgmLG4R9qV4J
          bUtkNM0mMVoYvuTFLkr57R/g3psS/JpN1qSVNZxM2/XB2guSdKLZ0q51Hs8ZdHKN
          wuIv3ZkMjDIsRVRYd/DhUZ52npPStslQN1AK/RLMpmyLpavWX+bSAu9zKjaQslWK
          bRCvnC8h28TCBV/BW7fcww7k1abAFjWpnQHvhlQJKE4QNbKaVU2o2uEQKFNg2bys
          bNwuLw1Tk1xAhvac0BIN7wIjRJ8KOMVAsZstWrEwzuoRe+INAf7uBWaDYOUGpi2i
          6lfZxbfx86vlOySqwhSwmVVKR8W1M/Sc32u0o4yNRRAB6GXXYCVLyxUhmDrXGx8e
          EwVDJuhLd4KcGKMRyvBB0QKCAQEA9hZrVEE7HCAJSEyqSwY7Cs8OSaHwMiACOWHw
          UEObNsVkB3voCiJu5JissnxUor2WAf+MBzcZkf0NUGFRAXYyLjqEHjhNV9ZI7QDH
          6nHGokygI3puyOM7jO+sQED5zjlevv8q0LXrQVMH+Hlabx2z+d2D4S2yeod+ca7B
          hrRtUOWJO0brMH253cePIcWsYzlj7d6vNOoDa6/DcC0XO64RhpQryGZ9M6au8ckI
          dH+7AXmIDJ5qHZSdxuggbduITdk8suIHa7ysdSxgm8vSDPqg4oHo260VFhOV7MBD
          IFP3V0rKR7yBMe1TolJBCTSJ7xEh4keERy9fQOmq7NwL9ghjqwKCAQEA8VFzuofs
          bqGlXrDLElFDtlPXks0Bd1ljod9dcQ624DIUgQ3/7XqyT5F6jPvAIdzY848/+M3k
          GJXnt+LvmEmHx6CJGRJrshsvSUGrP7WX1pk/aXg4n9YMOYz0UtfHC/xHlLRyy2Ll
          fBF3rw/QYpg0UD/4bgWgze8cvQ9zgb0zDYpXreVDuZOkYpNRLZi/jweOUKxVjlX/
          7DWZ+jhkJRBQesPxw4/ZIbnaUkUwEGXUvK4FudlSAPAk15hKswu19XE35N5wCST4
          0+3+bb33u7U3InHe/iUrL3ksH4J4mGGU2iVMzv/obLOmHcNUfLGLqK+o+bnL4YK2
          Tm7Fi4T0OtyEnQKCAQEA2zp9w0GZdyTTICWsT8ntL2PmRpKNeRoq4RPvEpIn5FNV
          GZW40c57HAsnTpqUi6Z5zK3sAUGE9hmJkuIfWD4D1ksrCAEAZg/wR7M6ZhGV82Bw
          CSs5Jp3In3Wk7lj0MlPJpD2N1wE546gkoab6eaLsgtxkcGZVafLrIjudDHQQLtFN
          wBEd1MUsn/b3/A4t1Pd7np2TWIBhK74ZTgXdfL1Fv66gkpc7UphboeqGLcLcxiOO
          oC9AObn8FQcWXMgGVdQBzxqtob0jpf8y0ZhyOD3Otfslhw5aiqBIH/Hn2xTydEGc
          kuvL7L6QkzrT1W+IsgGBPiSYIxKAuUNxkjE2NqiioQKCAQAV0CsJ3Wd9yJbOLGTu
          zvGz9XgzCNztEON0qmAj7BSTx3MbB0zvBnw/vQK647bGWNQzj+tUbigEIOjFMno9
          5cekP9qkrYmWm+Z2VL1KEPwcpdWZjwhvSkXondkn8+FGMBO4WWdXAyWDRYDwDhnk
          D6YK6v1l1JRoiQir/k2OmK+YtbyfN24bxEDDuFVKLdiC8Ufn+uvw5c0waNf2Skqj
          HwpnTnb4GnSiG86kSSTDFrFYLNLPrdk/xHVQF7AI5zIXcZh/06uE6Bal8YliGh3e
          lc7aCjkB+BIjRGy8nGqSO5/c6Co9O9yilsqZPiLQ8quRH+/CQw0u4UXhaRnqNqZs
          +6nxAoIBAQDvke0qsMODHS+boRF4ShacXG+yhN53+6+MvhGzw9OJgoD+QSWrSS5s
          Ka7Q//YFLq6xBUtn07tlHhL/8VkmF+o22heeJiREgHO+3DoTUI0bec7rQUzzy20k
          XujpLR01p3rg5hEN/dLVR77zVzngpkN6dWhPJ+ta5sxzrYaZlucIjyk9Nnbexncu
          X0JXNIbqoS0ceS/lfYEbPO3Tbw6kMAoxqqbAdlm/VHYOOBf3NqX9J2Pc0jyKkBLC
          stiAhQFx+b4kmXrzQkprS4kar9PUI7gDsZeRZ46lmwHInQ/Va9IUQL2XiH0Z44xl
          bTLGcrjpxDMSE/IrQvHRGs1RGyAxb6yt
          -----END PRIVATE KEY-----
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIFnTCCA4WgAwIBAgIUTgq17oer0IWI74yJ09exvn92xUcwDQYJKoZIhvcNAQEL
          BQAwXjELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE5ldyBZb3JrMRAwDgYDVQQHDAdC
          dWZmYWxvMQ0wCwYDVQQKDAREZXZVMRswGQYDVQQDDBJkZXZ1LXNpZ25pbmcubG9j
          YWwwHhcNMjEwNjA2MjAzMjM2WhcNMjMxMTIzMjAzMjM2WjBeMQswCQYDVQQGEwJV
          UzERMA8GA1UECAwITmV3IFlvcmsxEDAOBgNVBAcMB0J1ZmZhbG8xDTALBgNVBAoM
          BERldlUxGzAZBgNVBAMMEmRldnUtc2lnbmluZy5sb2NhbDCCAiIwDQYJKoZIhvcN
          AQEBBQADggIPADCCAgoCggIBAOf5Z2GoOzdQZrZPMWBSuGvoLokP4Nc38875TG7x
          zoEHHRHAp7MH65Bp+ZRhxJs38bcMKsWxm2vZA8FWbQrAxoImle1kzj3YD+3H72LO
          e/NxfDH7pByAZlJk/lCinXD7rTwZ8JPHPL3ptzk0Z5XplAEWpkbUutiMrztYRRPB
          hzVM8vyzD7Mwmy7Xafvg9cAIFPT8+1QLQbHb8PcloR4VL7p0kDn6wZ9qDiK6NrDO
          j7GWbqP4AjBabCfVRJMZFOGymd8mQavOkijBaUWC+QsXYcC4jffN2T/zfAQq3Mv5
          XPm47YDiRenQwXLs6/Jer6hecbHBsCp8yFf+zyh3lj8kP8+yZNyc+MD+wSZmJlsp
          8BlhRDmZV2lN2bhlJOGMlnsxj8H9uDC+mgtycsOMZn88oVXXJ4qIeiK3+E7mFTR0
          e2ZoJGAtyNpQw+t17FN4oE8+tcMI5JR+9rNduB9EcX7Ks8aspmEtvFl/eGfypZEN
          No9Janukv+bIHPenOz0jQAkKHAnD7epYrhWvJO/Qlq97k4jAxILkbG0cBJnD6zZr
          RWZDGN2Mak/F+w/L4KEzPig8mI9cKBQJELWx7BWkDkBnF9m4zBiAKorQtMUaTbgt
          AZMOU0AQCn/1YV2vIQYhy6X5lknXNYf0R/BWlr5K979peUgl4h5olgG31Uz6nvib
          fUvfAgMBAAGjUzBRMB0GA1UdDgQWBBTAdM+UMl6v33/eh6ZipMV9kcqr9zAfBgNV
          HSMEGDAWgBTAdM+UMl6v33/eh6ZipMV9kcqr9zAPBgNVHRMBAf8EBTADAQH/MA0G
          CSqGSIb3DQEBCwUAA4ICAQB4ufqyAMOi5n84bVQbHbDfDeAP27WdwXfOFRgKIP2N
          gXmpLUleBgmug513vqflG3LdTq/BZAsstGNB4MFRVvIFEf0nIdszwr4iqTKO1uKR
          8kQ5RagSBwUgRabXnxRJF0hOlzL3LBASTPfRtfoByHFMlCtUXLVUwYZMMBINLO5B
          FfIzdiTQ0PfgwBoZfHWUarbpMALPdLjwVzxoRsZ3h/U479GY7Ij1yWwg2gjGSMLo
          shcLvTfSSek6vY1RoNtOIn4YD9P0NlGgE8Fb3pwdDoD5pEQRtDOiBCr9hqxolH9b
          IjRNNRm3idNPtyj6uLN6W4RUHTCxoiWss1mJmSTHjptCTNILLp8yhj6slfzX4dcf
          jpTt7WHoF1XZNs9VhzjI0H8RkdXhlLj1AAKvbK0hjmCt4VNfIBXix7LrEWV/UUD/
          ZgVQCr5eWfqtGpe2aeLXYIv0HLK3D8uwAYKLvA4SH5mZvYkPYhXMD2Zb4UHPyBdN
          nQNMxyr0Gv8ueB2Mue8iZORnKpZWAN3kurryCxfj3aQ8/5guO5gu3lhYop4is7/e
          VBFHYQLWYI/Dbrn3PmnEu8Sce94T4Gz0+A+Puyhzt1nLOSmUJ4awxil28E5PNyWO
          02/AmOcox51wTC3WjyL/j5DtkE2rFtqpatnWscH090nFVNiatPhW0L5KURQxmwMa
          Aw==
          -----END CERTIFICATE-----

    devAuth:
      enabled: true

  jwt:
    activeKeyId: key-1
    accessTokenValiditySeconds: 20 # 10 minutes (seconds)
    refreshTokenValiditySeconds: 75 # 10 days (seconds)
    refreshTokenExpirationBufferSeconds: 60
    keys:
      key-1:
        privateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAthKQUufgSaKaRunbFJCxoNIzdzssRBJaqaT1s1oBov8d+QMm
          WCd97l27eT0logovA9vcC8EeaDrP3nGb1kMNv2gXlxlboaJ2ZP1AiC/YQAQxdC0Q
          Wb0YUufQP32w9u7wEQG0jPFA26AS6lEbCpLkbseUO9BSOEUxwijojnTJty34AeJg
          O3v1B74G78tb4xxMRmdjIi9SjCeA/ujgpX8vbODksexiTBQwYpCc8BlXEoUIwk8Z
          9G+i/Zz4sCLkJTMM4EIBcJ8y4ovrYIKRX0/EiSk54HOa+BgO/2Bz+pkyewjwIsT2
          663lJm9OpSA54+Y+kPe51FC+Xrx4R7SMvuL6CwIDAQABAoIBAQCZKyLI7BKuP6Fj
          +MX6FgOolE0BiAEkPwCQaJreR+DKm64+Vt0CGi8BwU6+nqczGzgUGfiS1uLasmc+
          7fo4lO5S0KHP1mBUqNTK/pY0O3PD3wMvhd2UcNSuoh952iZuhfHljLa0Pxzd5lsj
          Thnemlabr0BP1V/lwKgse7ewaCVt+E3EM4w8vBwUwGQh+N7CfMSvpqaDJ2DTIhXu
          JxfDW/7rbQHaC1636Y4CuhBtjkMBve1S/jbdQYNkT19m9MuhtlhiD7g9Cg2JFW2i
          L/g4WdhDY8Mv9852D2wNIcOX5PZLVeB5q+p2T6mjxDgHQzsteTuyjs0yYQy/48o0
          bhr9VGqhAoGBANija1yhArqeL6tnWCkJHTr9A5Y/4102Vp8q1U5AOqGtA6lxHZ1+
          u8z7JeE2N54kMSvq6gzGlw2pIr1usqlsdVxjpVVJsMNZPhjbKkyyw4C78TE39UOe
          7xradgvhl8auuloJrgsQjpYg11z5sgbmRcE8paK1vKAH10NZMyovFm/RAoGBANcn
          Xtf0dZykcMCWpjTrugs3RlLkGUzDCVXWANmzbguLVH03Q7+69gsPFQWHW/bh0GyJ
          2n2s2SklayWL7PI2wY1c4jy8nw0F6YcrwPuB/dn5hnmv4r3dMqhfOi9K/P/xFM0W
          FV/dEAhK+FEoQDuiIOGR/aqqJqIVpRr3GBdY5P8bAoGAdnjoPb/Pvj7D0vixPb++
          PIQhcgl+TXtp46GJBUIazk/PsNorV/X2viKalI8R22nvehT96f6wnMfiN7ZR/lVR
          2TSlNf8Wq74iN3WjrE4WnFArlr8DYfeIyyatZ9H3LrBfON4ST/q9/1v2auIieaN0
          gjioXFMG1H11O1+Mm4UkwAECgYEAqyOz+4+GZh0fWvH6Lyo6iGVlWNX7keWp7U8W
          yhRBuokPobJt/3qV7+IFVKqA6nZgtZVJ6KGu813CRtFwnpITj4CMrMdUtKU5Rr30
          +ZpC9DnZT74qW+AxRWDKBYheiq+XXjLsuZ47/Hy13Mhpn4WtJgBciH5j0JXrCPH3
          hcq+DHUCgYAfMsEt0FxFe7vJWP7C7Syd/dH70/Zwj8wg8jcGW0NXAQdE+VRfdfoJ
          Q9pNVwrX71ZeVliuH3XCYRAlfHNitaaFZvwwOlkiXdUkCuoKMDh1mhjCpvxBlAVY
          gRSo4OsC58yci7H3YSbgFwdryVgW8PTlI0VhTYDeWkSqy8097bE5RQ==
          -----END RSA PRIVATE KEY-----
        publicKey: |
          -----BEGIN RSA PUBLIC KEY-----
          MIIBCgKCAQEAthKQUufgSaKaRunbFJCxoNIzdzssRBJaqaT1s1oBov8d+QMmWCd9
          7l27eT0logovA9vcC8EeaDrP3nGb1kMNv2gXlxlboaJ2ZP1AiC/YQAQxdC0QWb0Y
          UufQP32w9u7wEQG0jPFA26AS6lEbCpLkbseUO9BSOEUxwijojnTJty34AeJgO3v1
          B74G78tb4xxMRmdjIi9SjCeA/ujgpX8vbODksexiTBQwYpCc8BlXEoUIwk8Z9G+i
          /Zz4sCLkJTMM4EIBcJ8y4ovrYIKRX0/EiSk54HOa+BgO/2Bz+pkyewjwIsT2663l
          Jm9OpSA54+Y+kPe51FC+Xrx4R7SMvuL6CwIDAQAB
          -----END RSA PUBLIC KEY-----

database:
  host: 'localhost'
  username: 'typescript_user'
  password: 'password'
  database: 'typescript_api'

logging:
  db: false

api:
  clientUrl: http://localhost:9000
  scheme: http
  host: localhost
  port: 3001
